Ajax_app/urls.py
from django.urls import path,include
from Ajax_app import views

urlpatterns = [
    path('',views.index,name='home'),
    path('edit_note',views.edit_note,name='EditNote'),
    path('delete_note',views.delete_note,name='DeleteNote'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.userlogin,name='login'),
    path('logout/',views.userlogout,name='logout'),
]

Ajax_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Ajax_app.urls')),
]

Ajax_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Note(models.Model):
    title = models.CharField(max_length =100)
    description = models.CharField(max_length =200,null=True)
    user =models.ForeignKey(User, on_delete= models.CASCADE)

    def __str__(self):
        return self.title

Ajax_app/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from Ajax_app.form import UserRegistrationform,UserLoginForm,NoteForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.http import JsonResponse
from Ajax_app.models import Note

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        form =NoteForm
        notes = Note.objects.filter(user=request.user).order_by('-id')
        data={
            'form':form,
            'notes':notes,
        }
        if request.method=="POST":
            title=request.POST.get('title')
            description=request.POST.get('description')
            print(title,description)

            note=Note()
            note.title=title
            note.description=description
            note.user =request.user
            note.save()
            notes=Note.objects.values().filter(user =request.user).order_by('-id')
            user_notes=list(notes)
            return JsonResponse({"status":"1","status_message":'Your Note Added Successfully','notes':'user_notes'})

        return render(request, 'notes/index.html',context=data)
    else:
        return redirect('login')
    
def edit_note(request):
    edit_id =request.POST.get('edit_id')
    title =request.POST.get('title')
    description =request.POST.get('description')
    Note.objects.filter(id=edit_id).update(title=title,description=description)
    notes=Note.objects.values().filter(user =request.user).order_by('-id')
    user_notes=list(notes)
    return JsonResponse({"status":"1","status_message":'Your Note Updated Successfully','notes':'user_notes'})

def delete_note(request):
    delete_id =request.GET.get('delete_id')
    print(delete_id)
    Note.objects.filter(id=delete_id).delete()
    notes=Note.objects.values().filter(user =request.user).order_by('-id')
    user_notes=list(notes)
    return JsonResponse({"status":"1","status_message":'Your Note Deleted Successfully','notes':'user_notes'})


def signup(request):
    form =UserRegistrationform()
    data={
        'form':form,
    }
    if request.method =='POST':
        username =request.POST.get('username')
        email =request.POST.get('email')
        password =request.POST.get('password')
        re_password =request.POST.get('re_password')

        if(password !=re_password):
            messages.error(request, "password do not match")
        else:
            user =User.objects.create_user(username=username,password=password,email=email)
            if(user.is_active):
                print('register')
                messages.success(request, "user created")
                
            else:
                print('error')

    return render(request,template_name='notes/signup.html',context=data)

def userlogin(request):
    form=UserLoginForm()
    data = {
        'form':form,
    }
    if request.method =="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')
        try:
            user = authenticate(request,username=username,password=password)
        except:
            return JsonResponse({"status":"Invalid Credential"})

        if user is not None:
            login(request,user)
            return JsonResponse({"status":"User login successfull"})
            
        else:
            return JsonResponse({"status":"Invalid Credential"})
        
        print( username, password)
        
    
    return render(request,template_name='notes/login.html',context=data)

def userlogout(request):
    logout(request)
    return redirect('login')

Ajax_app/templates/notes/index.html
{% extends "notes/layout.html" %}
{%load crispy_forms_tags %} 
{% block body %}
<br>
<div class="container">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Welcome {{request.user.username}}</h4>
        <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
        <hr>
        <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
      </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-5">
            <div class="col-10 mx-auto border rounded p-3">
                <h3 class="pt-3 pb-4">Add Your Notes Here</h3>
                <p class="text-white" id="message"></p>
                <form id="noteform">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" class="btn btn-success btn-sm p-2 m-3" value="Add Notes" id="add">
                </form>
            </div>
        </div>
        <div class="col-lg-7 mt-3 mb-3">
            <table class="table" id="notestable">
                <thead>
                    <tr>
                        <th scope="col">S.No</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for note in notes %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td class="title">{{note.title}}</td>
                        <td class="description">{{note.description}}</td>
                        <td><button data="{{note.id}}" class="btn btn-primary edit">Edit</button></td>
                        <td><button data="{{note.id}}" class="btn btn-danger delete">Delete</button></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" 
    crossorigin="anonymous">
</script>
<script>

    jQuery(document).ready(function($) {
        

        //edit function

        let activeIteam = null

        //show function
        function showNote(data){
            $('#notestable tbody').empty()
            for (i=0; i < data.length; i++){
                $('#notestable tbody').append(
                    `
                    <tr>
                        <th scope="row">${i+1}</th>
                        <td class="title">${data[i].title}</td>
                        <td class="description">${data[i].description}</td>
                        <td><button data="${data[i].id}" class="btn btn-primary edit">Edit</button></td>
                        <td><button data="${data[i].id}" class="btn btn-danger delete">Delete</button></td>
                    </tr>
                    `
                )
            }
        }
        function editIteam(item){
            var title = item.find('.title').text()
            var description=item.find('.description').text()
            var edit_id =item.find('.edit').attr('data')
            console.log(title,description,edit_id)
            $('#id_title').val(title)
            $('#id_description').val(description)
            $('#add').val('Update Note')
            $('#add').removeClass('bg-success');
            $('#add').addClass('bg-danger')
            activeIteam = edit_id
        }

        // delete note function
        function deleteNote(delete_id){
            $.ajax({
                type :'GET',
                url : "{% url "DeleteNote" %}",
                data : {
                    "delete_id" : delete_id,
                },
                success:function(response){
                    console.log(response.notes)
                    showNote(response.notes)
                    if (response.status_message =="Your Note Deleted Successfully"){
                        $('#message').text(response.status_message)
                        $('#message').removeClass('bg-warning')
                        $('#message').removeClass('bg-success')
                        $('#message').addClass('bg-danger')
                    }
                    $('.delete').click(function(){
                        var delete_id =$(this).attr('data')
                        console.log(delete_id)
                        deleteNote(delete_id)
                    })
                    $('.edit').click(function(){
                        var item=$(this).closest('tr')
                        editIteam(item)
                    })
                    
                }
            })
        }

        //this for form submission

        $('#noteform').on('submit', function(e) {
            e.preventDefault();
            var title = $('#id_title').val();
            var description = $('#id_description').val();
            url= '{% url "home" %}';
            data= {
                title: title,
                description: description,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            }
            if(activeIteam != null){
                url='{% url "EditNote" %}';
                data['edit_id'] =activeIteam
            }

            //ajax call
            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function (response) {
                    console.log(response)
                    data=response.notes;
                    $('#noteform').trigger("reset");
                    if (response.status === "1"){
                        showNote(data)
                    }
                    $('#message').text(response.status_message)
                    $('#message').removeClass('bg-warning')
                    $('#message').addClass('bg-success')
                    $('#message').addClass('p-2')
                    $('.edit').click(function(){
                        var item=$(this).closest('tr')
                        editIteam(item)
                    })
                    $('.delete').click(function(){
                        var delete_id =$(this).attr('data')
                        console.log(delete_id)
                        deleteNote(delete_id)
                    })

                    if (response.status_message === "Your Note Updated Successfully"){
                        $('#message').text(response.status_message)
                        $('#message').removeClass('bg-success')
                        $('#message').removeClass('bg-danger')
                        $('#message').addClass('bg-warning')
                        $('#add').val('Add Note')
                        $('#add').removeClass('bg-danger')
                        $('#add').addClass('bg-success')
                        activeIteam =null
                    }
                    
                    }
            })
        })
        $('.edit').click(function(){
            var item=$(this).closest('tr')
            editIteam(item)
        })
        $('.delete').click(function(){
            var delete_id =$(this).attr('data')
            console.log(delete_id)
            deleteNote(delete_id)
        })
    });
</script>
{% endblock body %}

Ajax_app/templates/notes/layout.html
<!doctype html>
<html lang="en">
    {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'notes/css/style.css' %}">
    
    <title>Hello, world!</title>
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Ajax_project</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
              </ul>
              <div class="d-flex">
                {% if request.user.is_authenticated %}
                <a href='{% url "logout" %}'><button class="btn btn-danger p-2 m-2">Logout</button></a>
                {% else %}
                <a href='{% url "login" %}'><button class="btn btn-success p-2 m-2">Login</button></a>
                <a href='{% url "signup" %}'><button class="btn btn-success p-2 m-2">signup</button></a>
                {% endif %}
              </div>
            </div>
          </nav>
    </header>

{% block body %}

{% endblock body %}

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  </body>
</html>

Ajax_app/templates/notes/login.html
{% extends "notes/layout.html" %}
{% load static %}
{%load crispy_forms_tags %} 
{% block body %}
<br>
<br>
<br>
    <div class="container col-4 border rounded p-3">
        <h2 class="p-3">Login Form</h2>
        <p id="message" class="text-white"></p>
        <form method="POST" id="loginform">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" class="btn btn-success m-2" value="login">
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" 
    crossorigin="anonymous">
</script>
<script>
    jQuery(document).ready(function($) {
        $('#loginform').on('submit', function(e) {
            e.preventDefault();
            var username = $('#id_username').val();
            var password = $('#id_password').val();

            $.ajax({
                type: 'POST',
                url: '/login/',
                data: {
                    username: username,
                    password: password,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success:function(response){
                    console.log(response.status);
                    $('#message').text(response.status)
                    $('#message').addClass("p-2");
                    if(response.status =="User login successfull"){
                        $('#message').addClass('bg-success');
                        window.location ="{% url "home" %}";
                    }
                    else{
                        $('#message').addClass('bg-danger');
                    }
                }
            });
        });
    });
</script>

{% endblock body %}

Ajax_app/templates/notes/signup.html
{% extends "notes/layout.html" %}
{%load crispy_forms_tags %} 
{% block body %}
<br>
<br>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li id="error_text" {% if message.tags %} class="bg-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container border p-4 rounded col-4">
    <p id="error" class="text-white"></p>
    <h2 class="p-3">signup form</h2>
    <form method="POST" action="{% url 'signup' %}" id="signupform">
    {{ form|crispy }}
    <input class="btn btn-sm btn-success m-2" type="submit" value="signup">
    {% csrf_token %}
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" 
    crossorigin="anonymous">
</script>

<!-- Your existing script -->
<script>
    jQuery(document).ready(function($) {
        $('#signupform').on('submit', function(e) {
            e.preventDefault();
            var username = $('#id_username').val();
            var email = $('#id_email').val();
            var password = $('#id_password').val();
            var re_password = $('#id_re_password').val();

            $.ajax({
                type: 'POST',
                url: '/signup/',
                data: {
                    username: username,
                    email: email,
                    password: password,
                    re_password: re_password,
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                },
                success: function (response) {
                    console.log(response);
                    var error=$(response).find('#error_text')
                    console.log(error);
                    var error_class=$(error).attr('class')
                    console.log(error_class)
                    console.log(error.text())
                    $('#error').addClass(error_class)
                    $('#error').addClass('p-2');
                    $('#error').text(error.text())
                    if(error.text()=="user created"){
                        window.location ={% url 'login' %}
                    }
                }
            });
        });
    });
</script>

{% endblock body %}